#if !defined(__POLYRAY_PARSE_DEFS)
#define __POLYRAY_PARSE_DEFS

/* Parser support functions and variables */
extern void ReadSceneFile(char *str);
extern int yylex(void);
extern int yylook(void);
extern int yyinput(void);
extern void yyoutput(int);
//CM??extern void yyunput(int, char *);
//extern void yyunput(int); //had to comment out -conflict with lex.yy.c generated by flex. cm 200206
extern int yyparse(void);
extern char *yyptok(int);
extern Vec White;

extern void Beginagain(void);//CM

#endif /* __POLYRAY_PARSE_DEFS */

