// lex.yy.cpp generated by reflex 4.2.1 from polyray.l

#define REFLEX_VERSION "4.2.1"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_bison               true
#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_header_file         "lex.yy.h"
#define REFLEX_OPTION_lex                 yylex
#define REFLEX_OPTION_lexer               yyFlexLexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "lex.yy.cpp"
#define REFLEX_OPTION_prefix              yy
#define REFLEX_OPTION_yy                  true
#define REFLEX_OPTION_yylineno            true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE DEFINITIONS                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define INITIAL (0)
#define YY_NUM_RULES (20)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "lex.yy.h"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

//#line   1 "polyray.l"

/*

Polyray — MIT Licensed Revival
Copyright(C) 1993 - 1996, Alexander Enzmann, All rights reserved.
Copyright(C) 1999 - 2026, Clyde Meli, All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
files(the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy,
modify, merge, publish, distribute, sublicense, and /or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions :

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 reflex --yy --header-file polyray.l
had to remove option noyywrap
??

add to lex.yy.h:
after #define REFLEX_OPTION...

#include "parse.h"//cm
#include "polyray.tab.h"//cm for YYSTYPE

*/
#include <utility>
#include <reflex/flexlexer.h>
#include "defs3.h"
#include "polyray.tab.h"
#include "io_ply.h"
#include "memory.h"
#include "runtime_state.h"
#include "symtab.h"
#include "parse.h"
#include "unixcompat.h"
#include "util.h" //for myCopy
//extern void polyray_pause(void);
extern void ReadSceneFile(std::string str);
//static void skipcom(void);

#define END(v) (v - 1 + sizeof(v) / sizeof(v[0]))
static int lookup(void);
static int copy_yystring(void);
void start_include(std::string);


YY_BUFFER_STATE include_stack[MAX_FILE_DEPTH]; //todo:change to max_include_depth
int include_stack_ptr = 0;

//#line   49 "polyray.l"
//%option bison-locations bison-bridge noyywrap header-file



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON                                                                     //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

yyFlexLexer YY_SCANNER;

#ifndef YY_EXTERN_C
#define YY_EXTERN_C
#endif

FILE *yyin = stdin;
FILE *yyout = stdout;

char *yytext;
yy_size_t yyleng;
int yylineno;

//YY_EXTERN_C
int yylex(void)
{
  if (yyin != YY_SCANNER.in())
    YY_SCANNER.in(yyin);  int yylex_token = YY_SCANNER.yylex();
  yytext = const_cast<char*>(YY_SCANNER.YYText());
  yyleng = static_cast<yy_size_t>(YY_SCANNER.YYLeng());
  yylineno = static_cast<int>(YY_SCANNER.lineno());
  return yylex_token;
}

#define yytext const_cast<char*>(YY_SCANNER.YYText())
#define yyleng static_cast<yy_size_t>(YY_SCANNER.YYLeng())
#define yylineno static_cast<int>(YY_SCANNER.lineno())

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int yyFlexLexer::yylex(void)
{
  static const char *REGEX_INITIAL = "(?m)([\\x09\\x0d\\x20])|((?:\\Q//\\E).*)|((?:\\Q//\\E).*$)|([/][\\x2a][^\\x2a]*[\\x2a]+(?:[^\\x2a/][^\\x2a]*[\\x2a]+)*[/])|([/][\\x2a])|([\\x09\\x0a\\x0d\\x20])|((?:\\Qinclude\\E)\\ \"[0-9A-Z_a-z]+\")|((?:\\Qinclude\\E).\\ |\\n)|(\"[^\\x0a\"]*\")|([0-9]+(?:[\\x2e]?[0-9]*(?:e[\\x2b\\x2d]?[0-9]+)?)?)|([0-9]*(?:[\\x2e]?[0-9]+(?:e[\\x2b\\x2d]?[0-9]+)?)?)|([0-9A-Z_a-z]+)|((?:\\Q&&\\E))|((?:\\Q||\\E))|((?:\\Q<=\\E))|((?:\\Q==\\E))|((?:\\Q>=\\E))|((?:\\Q!=\\E))|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
//#line   77 "polyray.l"
{
#ifdef DEBUG
printf("EOF REACHED\n");
printf("File_Name_Depth=%d\n",File_Name_Depth);
std::cout << "closing file" << File_List[File_Name_Depth - 1].name << "\n";
openpolyray::polyray_pause();
#endif

            if (File_Name_Depth > 0) {
                  if (yyin && yyin != stdin) {
	            if (fclose(yyin))
	               serror("Failed to close file '%s'\n",
	                   File_List[File_Name_Depth-1].name.c_str());
	          }
	          if (File_Name_Depth <= 1) {
	             //if ( yy_flex_debug ) {
				//	 printf("file nanme dept <=1, returning\n");
	             //    openpolyray::polyray_pause();
				 //}
	             yyterminate();//return 1;
	          }
	          File_Name_Depth--;
	          //if ( yy_flex_debug ) printf("going to file %d\n",File_Name_Depth-1);
	          CurrentFileName = File_List[File_Name_Depth-1].name;
              //if ( yy_flex_debug ) {
	          //  printf("prev yylineno=%d in %d\n",File_List[File_Name_Depth-1].line,File_Name_Depth-1);
	          //  printf("CurrentFileName is now %s\n",CurrentFileName);
		      //} //if yy flex debug

              yyin = File_List[File_Name_Depth - 1].file;
              yyrestart(File_List[File_Name_Depth-1].file);//flex

              yy_delete_buffer(RuntimeState::newbuf);
              // the specified input is no longer needed here
              yy_switch_to_buffer(RuntimeState::oldbuf);
              // continue scanning the old input

	          //yypop_buffer_state();
	          //yyin = fopen( (char*)CurrentFileName.c_str(), "r");
              //if (!yyin) serror("error opening previous file");
      	      //if ( yy_flex_debug ) printf("popped yylineno=%d, returning\n",yylineno);
//#undef yylineno
      		  //yylineno = File_List[File_Name_Depth-1].line;
              lineno(File_List[File_Name_Depth - 1].line+1);
      		  //if ( yy_flex_debug ) {
				//  printf("restored yylineno=%d, returning\n",yylineno);
	             // openpolyray::polyray_pause();
			  //} //end if yy flex debug


            //return 0; -- this doesnt work if I return 0, it stops parsing after the include file ends.
	          }


            if ( --include_stack_ptr < 0 )
	                {
	                yyterminate();
	                }

            else {
               // yy_switch_to_buffer(
               //     include_stack[include_stack_ptr]);
                //no need to do this twice
            }

            }

            }
            else
            {
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule polyray.l:53: [ \t\r] :
            YY_USER_ACTION
//#line   53 "polyray.l"
;
            YY_BREAK
          case 2: // rule polyray.l:54: "//".* :
            YY_USER_ACTION
//#line   54 "polyray.l"
{ /* do nothing */ }

            YY_BREAK
          case 3: // rule polyray.l:56: "//".*$ :
            YY_USER_ACTION
//#line   56 "polyray.l"
; /*can delete this */

            YY_BREAK
          case 4: // rule polyray.l:58: [/][*][^*]*[*]+([^*/][^*]*[*]+)*[/] :
            YY_USER_ACTION
//#line   58 "polyray.l"
{ /* C comments: DO NOTHING */ }
            YY_BREAK
          case 5: // rule polyray.l:59: [/][*] :
            YY_USER_ACTION
//#line   59 "polyray.l"
{ serror("Unterminated comment"); }

            YY_BREAK
          case 6: // rule polyray.l:61: [ \t\n\r] :
            YY_USER_ACTION
//#line   61 "polyray.l"
;
            YY_BREAK
          case 7: // rule polyray.l:62: "include"\ \"[A-Za-z0-9_]+\" :
            YY_USER_ACTION
//#line   62 "polyray.l"
{
            const std::string incspec(yytext, yyleng);
            const std::size_t q0 = incspec.find('"');
            const std::size_t q1 = incspec.rfind('"');
            if (q0 == std::string::npos || q1 == std::string::npos || q1 <= q0 + 1)
               serror("include_syntax error");
            start_include(incspec.substr(q0 + 1, q1 - q0 - 1));
            return INCLUDE;
}
            YY_BREAK
          case 8: // rule polyray.l:65: "include".\ |\n :
            YY_USER_ACTION
//#line   65 "polyray.l"
{ serror("include_syntax error"); /* Handle syntax error in #include */ }
            YY_BREAK
          case 9: // rule polyray.l:66: \"[^\"\n]*\" :
            YY_USER_ACTION
//#line   66 "polyray.l"
{ return copy_yystring(); }
            YY_BREAK
          case 10: // rule polyray.l:67: [0-9]+([.]?[0-9]*(e[\-\+]?[0-9]+)?)? :
            YY_USER_ACTION
//#line   67 "polyray.l"
{
            const std::string numtok(yytext, yyleng);
            yylval.flt = atof(numtok.c_str());
            return NUM;
}
            YY_BREAK
          case 11: // rule polyray.l:68: [0-9]*([.]?[0-9]+(e[\-\+]?[0-9]+)?)? :
            YY_USER_ACTION
//#line   68 "polyray.l"
{
            const std::string numtok(yytext, yyleng);
            yylval.flt = atof(numtok.c_str());
            return NUM;
}
            YY_BREAK
          case 12: // rule polyray.l:69: [A-Za-z0-9_]+ :
            YY_USER_ACTION
//#line   69 "polyray.l"
return lookup();
            YY_BREAK
          case 13: // rule polyray.l:70: "&&" :
            YY_USER_ACTION
//#line   70 "polyray.l"
return AND_SYM;
            YY_BREAK
          case 14: // rule polyray.l:71: "||" :
            YY_USER_ACTION
//#line   71 "polyray.l"
return OR_SYM;
            YY_BREAK
          case 15: // rule polyray.l:72: "<=" :
            YY_USER_ACTION
//#line  72 "polyray.l"
return LTEQ_SYM;
            YY_BREAK
          case 16: // rule polyray.l:73: "==" :
            YY_USER_ACTION
//#line  73 "polyray.l"
return EQUAL_SYM;
            YY_BREAK
          case 17: // rule polyray.l:74: ">=" :
            YY_USER_ACTION
//#line  74 "polyray.l"
return GTEQ_SYM;
            YY_BREAK
          case 18: // rule polyray.l:75: "!=" :
            YY_USER_ACTION
//#line  75 "polyray.l"
return NEQUAL_SYM;
            YY_BREAK
          case 19: // rule polyray.l:76: . :
            YY_USER_ACTION
//#line  76 "polyray.l"
return yytext[0];
            YY_BREAK
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

//#line   131 "polyray.l"

/* Screen for reserved words */
struct lookup_table_blk {
   std::string name;
   int val;
   } lookup_table[] = {
      {"Blinn",                  BLINN},
      {"Cook",                   COOK},
      {"Ferrari",                FERRARI},
      {"Gaussian",               GAUSSIAN},
      {"Phong",                  PHONG},
      {"Reitz",                  REITZ},
      {"Sturm",                  STURM},
      {"Vieta",                  VIETA},
      {"acceleration",           ACCELERATION},
      {"ambient",                AMBIENT},
      {"angle",                  ANGLE},
      {"antialias",              ANTIALIAS},
      {"antialias_threshold",    ANTIALIAS_THRESHOLD},
      {"aperture",               APERTURE},
      {"aspect",                 ASPECT},
      {"at",                     AT},
      {"avoid",                  AVOID},
      {"background",             BACKGROUND},
      {"bezier",                 BEZIER},
      {"birth",                  BIRTH},
      {"blob",                   BLOB},
      {"bounding_box",           BOUNDING_BOX},
      {"box",                    BOX},
      {"brilliance",             BRILLIANCE},
      {"bump_scale",             BUMP_SCALE},
      {"checker",                CHECKER},
      {"cheight_field",          CHEIGHT_FIELD},
      {"cheight_fn",             CHEIGHT_FN},
      {"color",                  COLOR},
      {"color_map",              COLOR_MAP},
      {"concave",                CONCAVE},
      {"cone",                   CONE},
      {"contour",                CONTOUR},
      {"count",                  COUNT},
      {"cylinder",               CYLINDER},
      {"death",                  DEATH},
      {"define",                 DEFINE},
      {"depth",                  DEPTH},
      {"depthmapped_light",      DEPTHMAPPED_LIGHT},
      {"diffuse",                DIFFUSE},
      {"directional_light",      DIRECTIONAL_LIGHT},
      {"disc",                   DISC},
      {"displace",               DISPLACE},
      {"dither",                 DITHER},
      {"draw",                   DRAW},
      {"else",                   ELSE},
      {"end_frame",              END_FRAME},
      {"file_flush",             FILE_FLUSH},
      {"flare",                  FLARE},
      {"flock",                  FLOCK},
      {"focal_distance",         FOCAL_DISTANCE},
      {"frame",                  FRAME},
      {"frame_time",             FRAME_TIME},
      {"frequency",              FREQUENCY},
      {"from",                   FROM},
      {"function",               FUNCTION},
      {"glyph",                  GLYPH},
      {"gridded",                GRIDDED},
      {"haze",                   HAZE},
      {"height_field",           HEIGHT_FIELD},
      {"height_fn",              HEIGHT_FN},
      {"hexagon",                HEXAGON},
      {"hither",                 HITHER},
      {"hypertexture",           HYPERTEXTURE},
      {"if",                     IF},
      {"image_format",           IMAGE_FORMAT},
      {"image_window",           IMAGE_WINDOW},
      {"include",                INCLUDE},
      {"indexed",                INDEXED},
      {"lathe",                  LATHE},
      {"layered",                LAYERED},
      {"light",                  LIGHT},
      {"lookup_fn",              LOOKUP_FUNCTION},
      {"max_samples",            MAX_SAMPLES},
      {"max_trace_depth",        MAX_TRACE_DEPTH},
      {"microfacet",             MICROFACET},
      {"no_shadow",              NO_SHADOW},
      {"noeval",                 NOEVAL},
      {"noise",                  NOISE},
      {"normal",                 NORMAL},
      {"nurb",                   NURB},
      {"nurb2",                  NURB2},
      {"object",                 OBJECT},
      {"octaves",                OCTAVES},
      {"outfile",                OUTFILE},
      {"parabola",               PARABOLA},
      {"parametric",             PARAMETRIC},
      {"particle",               PARTICLE},
      {"patch",                  PATCH},
      {"phase",                  PHASE},
      {"runtimeState::settings.pixel_encoding",         PIXEL_ENCODING},
      {"pixelsize",              PIXELSIZE},
      {"plane",                  PLANE},
      {"point",                  POINT},
      {"polygon",                POLYGON},
      {"polynomial",             POLYNOMIAL},
      {"position",               POSITION},
      {"position_fn",            POSITION_FUNCTION},
      {"position_scale",         POSITION_SCALE},
      {"raw",                    RAW},
      {"reflection",             REFLECTION},
      {"resolution",             RESOLUTION},
      {"root_solver",            ROOT_SOLVER},
      {"rotate",                 ROTATE},
      {"scale",                  SCALE},
      {"seed",                   SEED},
      {"shading_flags",          SHADING_FLAGS},
      {"shear",                  SHEAR},
      {"sheight_field",          SHEIGHT_FIELD},
      {"sheight_fn",             SHEIGHT_FN},
      {"size",                   SIZE},
      {"smooth_cheight_field",   SMOOTH_CHEIGHT_FIELD},
      {"smooth_cheight_fn",      SMOOTH_CHEIGHT_FN},
      {"smooth_height_field",    SMOOTH_HEIGHT_FIELD},
      {"smooth_height_fn",       SMOOTH_HEIGHT_FN},
      {"smooth_sheight_field",   SMOOTH_SHEIGHT_FIELD},
      {"smooth_sheight_fn",      SMOOTH_SHEIGHT_FN},
      {"spacing",                SPACING},
      {"special",                SPECIAL},
      {"specular",               SPECULAR},
      {"sphere",                 SPHERE},
      {"spot_light",             SPOT_LIGHT},
      {"start_frame",            START_FRAME},
      {"static",                 STATIC},
      {"summed",                 SUMMED},
      {"superq",                 SUPERQ},
      {"surface",                SURFACE},
      {"sweep",                  SWEEP},
      {"system",                 SYSTEM},
      {"texture",                TEXTURE},
      {"texture_map",            TEXTURE_MAP},
      {"textured_light",         TEXTURED_LIGHT},
      {"torus",                  TORUS},
      {"total_frames",           TOTAL_FRAMES},
      {"transform",              TRANSFORM},
      {"translate",              TRANSLATE},
      {"transmission",           TRANSMISSION},
      {"turbulence",             TURBULENCE},
      {"u_steps",                U_STEPS},
      {"up",                     UP},
      {"uv",                     UV},
      {"uv_bounds",              UV_BOUNDS},
      {"uv_steps",               UV_STEPS},
      {"v_steps",                V_STEPS},
      {"velocity",               VELOCITY},
      {"viewpoint",              VIEWPOINT},
      {"w_steps",                W_STEPS},
      {"yon",                    YON}
      };
typedef struct lookup_table_blk *tabptr;

int lookup(void)
{
   tabptr low  = lookup_table;
   tabptr high = END(lookup_table);
   tabptr mid;
//   char *strtmp;
   int c, l1;
   void *d;

   std::string syyt(yytext, yyleng);
#ifdef DEBUG_FN_CALLS

if (yytext == nullptr) {

    exit(2);
}



//smessage("yytext=%s\n",(char*)syyt.c_str());

#endif
   while (low <= high) {
      mid = low + (high - low) / 2;
      //if ((c = strcmp(mid->name.c_str(), yytext)) == 0) {
      if ( mid->name == syyt) {
         return mid->val;
         }
      else if (mid->name < syyt) //if (c < 0)
         low = mid + 1;
      else
         high = mid - 1;
      }

   /* If the string isn't predefined, then look for it in the symbol table */
   l1 = syyt.length();
   //smessage("calling lookup_string and yytext is ");
   //smessage(syyt);
   std::string strtmp = Lookup_String((char*) syyt.c_str());
   if (strtmp == "") {
      //strtmp = (char *)polyray_malloc((l1+1) * sizeof(char));
      //if (strtmp == NULL)
      //   serror("Failed to allocate space for a string constant\n");
      //memcpy(strtmp, yytext, l1+1);
      strtmp = yytext;
      yylval.name = myCopy(strtmp);// (char*)strtmp.c_str();//the only way to do it, sadly

      //smessage("returning token\n");
      return TOKEN;
      }
   else {

      Lookup_Definition((char*)syyt.c_str(), &c, &d);
      switch (c) {
      case std::to_underlying(ShapeType::Object):
         yylval.name = myCopy(strtmp);
         return OBJECT_SYM;
      case std::to_underlying(ShapeType::Surface):
         yylval.name = myCopy(strtmp);
         return SURFACE_SYM;
      case std::to_underlying(ShapeType::Texture):
         yylval.name = myCopy(strtmp);
         return TEXTURE_SYM;
      case std::to_underlying(ShapeType::Texture_Map):
         yylval.name = myCopy(strtmp);
         return TEXTURE_MAP_SYM;
      case std::to_underlying(ShapeType::Transform):
         yylval.name = myCopy(strtmp);
         return TRANSFORM_SYM;
      case std::to_underlying(ShapeType::Expression):
         yylval.name = myCopy(strtmp);
         return EXPRESSION_SYM;
      case std::to_underlying(ShapeType::Particle):
         yylval.name = myCopy(strtmp);
         return PARTICLE_SYM;
      default:
         serror("Bad type in symbol table: '%s' - %d\n", syyt.c_str(), c);
	 return 0; /* To remove warning about non-return value */
      } }
}

//#line   575 "lex.yy.cpp"
//yytext = include
//copy_yystring
//returning from copy_yystring name is nclude "co
int copy_yystring(void)
{
   int len = static_cast<int>(yyleng);
   char *strtmp;
#ifdef DEBUG_FN_CALLS
smessage("lex.yy.cpp::copy_yystring\n");
#endif
   if (len < 2)
      serror("Malformed string token in lexer\n");
   strtmp = (char *)polyray_malloc((len - 1) * sizeof(char));
   if (strtmp == NULL)
      serror("Failed to allocate space for a string constant\n");
   memcpy(strtmp, &yytext[1], len-2);
   strtmp[len-2] = '\0';
   yylval.name = strtmp;

   return STRING;
}

void ReadSceneFile(std::string str)
{
#ifdef DEBUG_FN_CALLS
smessage("lex.yy.cpp::ReadSceneFile\n");
std::cout<<"ReadSceneFile("<<str<<")\n";
openpolyray::polyray_pause();
#endif
   SetInputFile((char*)str.c_str());
   YY_SCANNER.start(INITIAL);
   yyrestart(yyin);
   if (yyparse() == 1)
      serror("Invalid input specification\n");
}

void Beginagain(void)
{
  //BEGIN(INITIAL);//YY_SCANNER.start_=INITIAL
  YY_SCANNER.start(INITIAL);//RE-flex equivalent

}

void start_include(std::string name)
{
	#ifdef DEBUG_FN_CALLS
	std::cout << "*** start_include\n";
	std::cout<<"included name is ("<<name<<")\n";
        std::cout<<"File_Name_Depth="<<File_Name_Depth<<"\n";
        printf("current File_Name=%s\n",(char*)File_List[File_Name_Depth-1].name.c_str());
        if (name == "") {
            serror("Error: start_include requires a file!\n");
        }

	//openpolyray::polyray_pause();
	#endif

   char myenviron[]="c:\\polyray\0";

   if (File_Name_Depth > MAX_FILE_DEPTH) {
       serror("Include files nested too deep\n");
       exit(9);
   }

   include_stack[include_stack_ptr++] =
            YY_CURRENT_BUFFER;

   /* Now that we have the name of the include file, we
      stash it away for when the EOF is reached. */
   File_List[File_Name_Depth].file = PathFileOpen(nullptr, name, "rt"); // was environ,name,"rt"
   if (File_List[File_Name_Depth].file == nullptr) {
       swarning("Failed to open include file: '");
       swarning(name);
       swarning("'\n");
   }
   else {

      #ifdef DEBUG
      printf("saving yylineno=%d in [%d]\n",yylineno, File_Name_Depth-1);
      #endif
      File_List[File_Name_Depth-1].line = yylineno;
      File_List[File_Name_Depth].name = name;

      yyin = File_List[File_Name_Depth].file;
      CurrentFileName = name;
      RuntimeState::oldbuf = YY_CURRENT_BUFFER;
      RuntimeState::newbuf = yy_create_buffer(yyin, YY_BUF_SIZE);
      yy_switch_to_buffer(RuntimeState::newbuf);


      Beginagain();    //
      YY_SCANNER.lineno(1);

      File_Name_Depth++;
      }
}
